### ISSUE TITLE
Plot labeling distorted

### ISSUE THREAD

**Issue by leezu** [adrianliaw/docker-jupyter-irkernel#3]
Hey,

first of all thanks for providing this nice docker image. It's very helpful to me!

However I ran into problems with different plots:
![image](https://cloud.githubusercontent.com/assets/946903/8294320/f997173a-193b-11e5-8041-d3ecec7983a4.png)

Maybe this is related to some misunderstanding on my side to the way R is supposed to work, or it is a irkernel bug. I was following https://github.com/wehrley/wehrley.github.io/blob/master/SOUPTONUTS.md for my R commands

**Comment by leezu** [comment]
Fixed it by rebuilding the image. Had to make some changes to the Dockerfile: https://github.com/leezu/docker-jupyter-irkernel/commit/a0440d02dd7b03a67de67d004e8c7bfe8dea2705

**Comment by adrianliaw** [comment]
Thanks for reporting the issue, I should upgrade the image to the newest version of irkernel.
